/* SIGNIN */
export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

/* TOKEN */
export const GET_TOKEN_REQUEST = 'GET_TOKEN_REQUEST';
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';
export const GET_TOKEN_FAILURE = 'GET_TOKEN_FAILURE';

/* LOGOUT */
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

/* FORGOT PASSWORD  */
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

/* ALL  ITEMS */
export const ALL_ITEMS_REQUEST = 'ALL_ITEMS_REQUEST';
export const ALL_ITEMS_SUCCESS = 'ALL_ITEMS_SUCCESS';
export const ALL_ITEMS_FAILURE = 'ALL_ITEMS_FAILURE';

/* JEWELERY ITEM STOCK */
export const JEWELERY_ITEMS_STOCK_REQUEST = 'JEWELERY_ITEMS_STOCK_REQUEST';
export const JEWELERY_ITEMS_STOCK_SUCCESS = 'JEWELERY_ITEMS_STOCK_SUCCESS';
export const JEWELERY_ITEMS_STOCK_FAILURE = 'JEWELERY_ITEMS_STOCK_FAILURE';

/* ELECTRONICS ITEM STOCK */
export const ELECTRONICS_ITEMS_STOCK_REQUEST =
  'ELECTRONICS_ITEMS_STOCK_REQUEST';
export const ELECTRONICS_ITEMS_STOCK_SUCCESS =
  'ELECTRONICS_ITEMS_STOCK_SUCCESS';
export const ELECTRONICS_ITEMS_STOCK_FAILURE =
  'ELECTRONICS_ITEMS_STOCK_FAILURE';

/* MENS_CLOTHING ITEM STOCK */
export const MENS_CLOTHING_ITEMS_STOCK_REQUEST =
  'MENS_CLOTHING_ITEMS_STOCK_REQUEST';
export const MENS_CLOTHING_ITEMS_STOCK_SUCCESS =
  'MENS_CLOTHING_ITEMS_STOCK_SUCCESS';
export const MENS_CLOTHING_ITEMS_STOCK_FAILURE =
  'MENS_CLOTHING_ITEMS_STOCK_FAILURE';

/* WOMENS_CLOTHING_ITEMS  STOCK */
export const WOMENS_CLOTHING_ITEMS_STOCK_REQUEST =
  'WOMENS_CLOTHING_ITEMS_STOCK_REQUEST';
export const WOMENS_CLOTHING_ITEMS_STOCK_SUCCESS =
  'WOMENS_CLOTHING_ITEMS_STOCK_SUCCESS';
export const WOMENS_CLOTHING_ITEMS_STOCK_FAILURE =
  'WOMENS_CLOTHING_ITEMS_STOCK_FAILURE';

/* CATEGORIES */
export const CATEGORIES_REQUEST = 'CATEGORIES_REQUEST';
export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS';
export const CATEGORIES_FAILURE = 'CATEGORIES_FAILURE';
